services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod

  backend:
    build: .
    container_name: django-app
    depends_on:
      - db
    volumes:
      - ./static:/backend/backend/staticfiles
    env_file:
      - .env.prod
    ports:
      - "8001:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "8080:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data: