version: '3.8'

services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod
    networks:
      - app-network

  backend:
    build: .
    container_name: django-app
    depends_on:
      - db
    volumes:
      - ./backend:/backend/backend
    env_file:
      - .env.prod
    ports:
      - "8001:8001"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "8080:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  ai_script:
    build:
      context: ai_script
      dockerfile: Dockerfile
    container_name: ai-script-app
    ports:
      - "8050:8050"
    volumes:
      - ./ai_script:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8050 --reload
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
