services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod

  backend:
    build: .
    container_name: django-app
    depends_on:
      - db
    volumes:
      - ./backend:/backend/backend
    env_file:
      - .env.prod
    ports:
      - "8001:8001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

  ai_script:  #
    build:
      context: ai_script  # On va chercher dans le dossier ai_script
      dockerfile: Dockerfile
    container_name: ai-script-app
    ports:
      - "8050:8050"  # 8050 dehors -> 8050 dans le container
    volumes:
      - ./ai_script:/app  # (optionnel mais pratique pour faire du hot reload)
    command: uvicorn main:app --host 0.0.0.0 --port 8050 --reload

volumes:
  postgres_data: