# Generated by Django 5.1.6 on 2025-03-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
