# Generated by Django 5.1.6 on 2025-04-12 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_links', to='story.case')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='story.character')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='characters',
            field=models.ManyToManyField(related_name='cases', through='story.CharacterCase', to='story.character'),
        ),
    ]
