# Generated by Django 5.1.6 on 2025-04-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_charactercase_case_characters'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='charactercase',
            constraint=models.UniqueConstraint(fields=('character', 'case'), name='unique_character_case'),
        ),
    ]
