# Generated by Django 4.2.11 on 2025-04-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_charactercase_unique_character_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='parent',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
