# Generated by Django 4.2.11 on 2025-04-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_case_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
