# Generated by Django 4.2.11 on 2025-04-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_case_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
    ]
