# Generated by Django 5.1.7 on 2025-04-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_case_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='parent',
        ),
        migrations.AddField(
            model_name='case',
            name='children',
            field=models.ManyToManyField(related_name='parents', to='story.case'),
        ),
    ]
