# Generated by Django 5.1.7 on 2025-04-23 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0009_remove_case_parent_case_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='children',
        ),
        migrations.AddField(
            model_name='case',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='story.case'),
        ),
    ]
