# Generated by Django 5.1.7 on 2025-04-23 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0010_remove_case_children_case_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='story.story'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
