# Generated by Django 5.1.6 on 2025-05-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0011_case_story_alter_story_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='text',
        ),
        migrations.AddField(
            model_name='case',
            name='prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='repliques',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
