# Generated by Django 5.1.6 on 2025-05-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_remove_case_text_case_prompt_case_repliques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='repliques',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
