# Generated by Django 5.1.6 on 2025-05-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0013_alter_case_repliques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='repliques',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
