# Generated by Django 4.2.11 on 2025-05-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0014_alter_case_repliques'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hexcolor',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='imagepath',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
