# Generated by Django 5.1.6 on 2025-05-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0015_character_hexcolor_character_imagepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='characters',
        ),
        migrations.DeleteModel(
            name='CharacterCase',
        ),
        migrations.AddField(
            model_name='case',
            name='characters',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
